from pathlib import Path
from typing import Any

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from app.crypto.keys import private_key_from_seed, public_key_b64url
from app.tools import gen_root_key

PLACEHOLDER = "REPLACE_WITH_REAL_ROOT_PUBLIC_KEY (generated by backend/app/tools/gen_root_key.py)\n"
ENV_LINE_PREFIX = "ROOT_SIGNING_KEY_B64="


def _printed_seed(stdout: str) -> str:
    lines = [line for line in stdout.splitlines() if line.startswith(ENV_LINE_PREFIX)]
    assert len(lines) == 1
    return lines[0].removeprefix(ENV_LINE_PREFIX)


def test_default_target_is_the_committed_trust_file() -> None:
    expected = Path(__file__).resolve().parents[2] / "content" / "trust" / "root_public_key.txt"

    assert expected == gen_root_key.DEFAULT_PUBLIC_KEY_FILE


def test_replaces_placeholder_and_prints_the_matching_seed(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    key_file = tmp_path / "root_public_key.txt"
    key_file.write_text(PLACEHOLDER, encoding="utf-8")

    assert gen_root_key.main(["--public-key-file", str(key_file)]) == 0

    written = key_file.read_text(encoding="utf-8")
    assert written.endswith("\n")
    assert written.count("\n") == 1
    public = written.strip()
    assert len(public) == 43
    seed = _printed_seed(capsys.readouterr().out)
    assert public_key_b64url(private_key_from_seed(seed).public_key()) == public


def test_creates_the_file_when_missing(tmp_path: Path) -> None:
    key_file = tmp_path / "root_public_key.txt"

    assert gen_root_key.main(["--public-key-file", str(key_file)]) == 0
    assert len(key_file.read_text(encoding="utf-8").strip()) == 43


def test_refuses_to_replace_a_real_key(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    key_file = tmp_path / "root_public_key.txt"
    existing = public_key_b64url(Ed25519PrivateKey.generate().public_key()) + "\n"
    key_file.write_text(existing, encoding="utf-8")

    assert gen_root_key.main(["--public-key-file", str(key_file)]) != 0

    assert key_file.read_text(encoding="utf-8") == existing
    captured = capsys.readouterr()
    assert "--force" in captured.err
    assert ENV_LINE_PREFIX not in captured.out  # no new private key was handed out


def _real_public_key() -> str:
    return public_key_b64url(Ed25519PrivateKey.generate().public_key())


@pytest.mark.parametrize(
    "content",
    [
        lambda key: ("﻿" + key + "\n").encode("utf-8"),  # UTF-8 BOM
        lambda key: (key + "\n").encode("utf-16"),  # PowerShell 5.1 Out-File default
        lambda key: (key + "=\n").encode("utf-8"),  # padded
        lambda key: (key + "\n# comment\n").encode("utf-8"),
        lambda key: (key.replace("-", "+").replace("_", "/") + "\n").encode("utf-8"),
        lambda key: b"",
        lambda key: b"something else entirely\n",
    ],
    ids=["bom", "utf16", "padded", "comment-line", "std-alphabet", "empty", "garbage"],
)
def test_fails_closed_on_anything_but_the_placeholder(
    content: Any, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    key_file = tmp_path / "root_public_key.txt"
    original = content(_real_public_key())
    key_file.write_bytes(original)

    assert gen_root_key.main(["--public-key-file", str(key_file)]) != 0

    assert key_file.read_bytes() == original
    assert ENV_LINE_PREFIX not in capsys.readouterr().out


def test_placeholder_with_crlf_is_still_the_placeholder(tmp_path: Path) -> None:
    key_file = tmp_path / "root_public_key.txt"
    key_file.write_bytes(PLACEHOLDER.replace("\n", "\r\n").encode("utf-8"))

    assert gen_root_key.main(["--public-key-file", str(key_file)]) == 0


def test_the_committed_file_is_the_exact_placeholder() -> None:
    # Keeps PLACEHOLDER in sync with content/trust/root_public_key.txt until T-17 replaces it
    committed = gen_root_key.DEFAULT_PUBLIC_KEY_FILE.read_text(encoding="utf-8")

    assert committed.strip() == gen_root_key.PLACEHOLDER or len(committed.strip()) == 43


def test_force_replaces_a_real_key(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    key_file = tmp_path / "root_public_key.txt"
    existing = public_key_b64url(Ed25519PrivateKey.generate().public_key()) + "\n"
    key_file.write_text(existing, encoding="utf-8")

    assert gen_root_key.main(["--public-key-file", str(key_file), "--force"]) == 0

    public = key_file.read_text(encoding="utf-8").strip()
    assert public != existing.strip()
    seed = _printed_seed(capsys.readouterr().out)
    assert public_key_b64url(private_key_from_seed(seed).public_key()) == public
