"""Generate the root Ed25519 signing key, once (docs/04 "Keys", D-014).

Writes the public key to content/trust/root_public_key.txt (commit that file) and prints the
private seed once, for the Render env var ROOT_SIGNING_KEY_B64. Run it yourself in a terminal:
the private key must not pass through logs, chat transcripts or files.

    uv run python -m app.tools.gen_root_key [--public-key-file PATH] [--force]
"""

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from app.crypto.keys import public_key_b64url, seed_b64url

DEFAULT_PUBLIC_KEY_FILE = (
    Path(__file__).resolve().parents[3] / "content" / "trust" / "root_public_key.txt"
)
# Exact content committed before the real key exists (whitespace around it is ignored)
PLACEHOLDER = "REPLACE_WITH_REAL_ROOT_PUBLIC_KEY (generated by backend/app/tools/gen_root_key.py)"


def _safe_to_write(path: Path) -> bool:
    """Fail closed: without --force, only a missing file or the placeholder may be replaced.

    Anything else might be the real key in another spelling (BOM, UTF-16, padding, ...).
    """
    try:
        return path.read_bytes().decode("utf-8").strip() == PLACEHOLDER
    except FileNotFoundError:
        return True
    except (OSError, UnicodeDecodeError):
        return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m app.tools.gen_root_key",
        description="Generate the root Ed25519 key: public key to the trust file, seed to stdout.",
    )
    parser.add_argument(
        "--public-key-file",
        type=Path,
        default=DEFAULT_PUBLIC_KEY_FILE,
        help="where to write the public key (default: content/trust/root_public_key.txt)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing root key; everything signed under the old key stops verifying",
    )
    args = parser.parse_args(argv)
    key_file: Path = args.public_key_file

    if not args.force and not _safe_to_write(key_file):
        print(
            f"{key_file} is not the placeholder, so it may already hold the root public key. "
            "Replacing it invalidates every device attestation and certificate. "
            "Re-run with --force only to rotate the root key.",
            file=sys.stderr,
        )
        return 1

    key = Ed25519PrivateKey.generate()
    public = public_key_b64url(key.public_key())
    key_file.write_text(public + "\n", encoding="utf-8", newline="\n")

    print(f"Root public key written to {key_file}:\n  {public}\nCommit that file.\n")
    print("Private key: set it ONLY as this Render env var. Never commit, log or share it.")
    print(f"ROOT_SIGNING_KEY_B64={seed_b64url(key)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
